source 'https://github.com/CocoaPods/Specs.git'
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
platform :ios, '8.0'
target ‘Chapper’ do
pod 'MJExtension'
pod 'PYSearch'
pod 'SDWebImage', '~> 4.0'
pod 'AFNetworking', '~> 3.0'
pod ‘Masonry’
pod 'MJCSegmentInterface'
pod 'UMengAnalytics-NO-IDFA'
pod 'BHInfiniteScrollView'
pod 'PYSearch'
pod 'SVProgressHUD'
pod 'AlibcTradeSDK'
pod 'UMengAnalytics-NO-IDFA'
pod 'JPush'
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts target.name
    end
end
